# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\TuftsDailyPostDownloader.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PostDownloader(object):
    def setupUi(self, PostDownloader):
        PostDownloader.setObjectName("PostDownloader")
        PostDownloader.resize(733, 509)
        self.centralwidget = QtWidgets.QWidget(PostDownloader)
        self.centralwidget.setMinimumSize(QtCore.QSize(731, 0))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.optionsGrid = QtWidgets.QGridLayout()
        self.optionsGrid.setObjectName("optionsGrid")
        self.catFilterGroup = QtWidgets.QGroupBox(self.centralwidget)
        self.catFilterGroup.setCheckable(True)
        self.catFilterGroup.setChecked(False)
        self.catFilterGroup.setObjectName("catFilterGroup")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.catFilterGroup)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.catTextEdit = QtWidgets.QPlainTextEdit(self.catFilterGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.catTextEdit.sizePolicy().hasHeightForWidth())
        self.catTextEdit.setSizePolicy(sizePolicy)
        self.catTextEdit.setObjectName("catTextEdit")
        self.verticalLayout_4.addWidget(self.catTextEdit)
        self.optionsGrid.addWidget(self.catFilterGroup, 3, 1, 2, 1)
        self.postCountGroup = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.postCountGroup.sizePolicy().hasHeightForWidth())
        self.postCountGroup.setSizePolicy(sizePolicy)
        self.postCountGroup.setObjectName("postCountGroup")
        self.formLayout = QtWidgets.QFormLayout(self.postCountGroup)
        self.formLayout.setObjectName("formLayout")
        self.onlyRB = QtWidgets.QRadioButton(self.postCountGroup)
        self.onlyRB.setChecked(False)
        self.onlyRB.setObjectName("onlyRB")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.onlyRB)
        self.postCount = QtWidgets.QSpinBox(self.postCountGroup)
        self.postCount.setEnabled(False)
        self.postCount.setMaximum(2147483647)
        self.postCount.setProperty("value", 100)
        self.postCount.setObjectName("postCount")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.postCount)
        self.allRB = QtWidgets.QRadioButton(self.postCountGroup)
        self.allRB.setChecked(True)
        self.allRB.setObjectName("allRB")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.allRB)
        self.optionsGrid.addWidget(self.postCountGroup, 0, 0, 3, 1)
        self.dateFilterGroup = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateFilterGroup.sizePolicy().hasHeightForWidth())
        self.dateFilterGroup.setSizePolicy(sizePolicy)
        self.dateFilterGroup.setObjectName("dateFilterGroup")
        self.formLayout_2 = QtWidgets.QFormLayout(self.dateFilterGroup)
        self.formLayout_2.setObjectName("formLayout_2")
        self.postsAfterCheckBox = QtWidgets.QCheckBox(self.dateFilterGroup)
        self.postsAfterCheckBox.setObjectName("postsAfterCheckBox")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.postsAfterCheckBox)
        self.afterDateEdit = QtWidgets.QDateEdit(self.dateFilterGroup)
        self.afterDateEdit.setEnabled(False)
        self.afterDateEdit.setObjectName("afterDateEdit")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.afterDateEdit)
        self.postsBeforeCheckBox = QtWidgets.QCheckBox(self.dateFilterGroup)
        self.postsBeforeCheckBox.setObjectName("postsBeforeCheckBox")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.postsBeforeCheckBox)
        self.beforeDateEdit = QtWidgets.QDateEdit(self.dateFilterGroup)
        self.beforeDateEdit.setEnabled(False)
        self.beforeDateEdit.setObjectName("beforeDateEdit")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.beforeDateEdit)
        self.optionsGrid.addWidget(self.dateFilterGroup, 0, 1, 3, 1)
        self.tagFilterGroup = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tagFilterGroup.sizePolicy().hasHeightForWidth())
        self.tagFilterGroup.setSizePolicy(sizePolicy)
        self.tagFilterGroup.setFlat(False)
        self.tagFilterGroup.setCheckable(True)
        self.tagFilterGroup.setChecked(False)
        self.tagFilterGroup.setObjectName("tagFilterGroup")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tagFilterGroup)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.tagTextEdit = QtWidgets.QPlainTextEdit(self.tagFilterGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tagTextEdit.sizePolicy().hasHeightForWidth())
        self.tagTextEdit.setSizePolicy(sizePolicy)
        self.tagTextEdit.setObjectName("tagTextEdit")
        self.verticalLayout_5.addWidget(self.tagTextEdit)
        self.optionsGrid.addWidget(self.tagFilterGroup, 3, 0, 2, 1)
        self.saveLocGroup = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveLocGroup.sizePolicy().hasHeightForWidth())
        self.saveLocGroup.setSizePolicy(sizePolicy)
        self.saveLocGroup.setObjectName("saveLocGroup")
        self.gridLayout = QtWidgets.QGridLayout(self.saveLocGroup)
        self.gridLayout.setObjectName("gridLayout")
        self.pathEditButton = QtWidgets.QPushButton(self.saveLocGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pathEditButton.sizePolicy().hasHeightForWidth())
        self.pathEditButton.setSizePolicy(sizePolicy)
        self.pathEditButton.setObjectName("pathEditButton")
        self.gridLayout.addWidget(self.pathEditButton, 0, 1, 1, 1)
        self.pathTextEdit = QtWidgets.QTextBrowser(self.saveLocGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pathTextEdit.sizePolicy().hasHeightForWidth())
        self.pathTextEdit.setSizePolicy(sizePolicy)
        self.pathTextEdit.setObjectName("pathTextEdit")
        self.gridLayout.addWidget(self.pathTextEdit, 0, 0, 1, 1)
        self.optionsGrid.addWidget(self.saveLocGroup, 5, 1, 1, 1)
        self.searchTermGroup = QtWidgets.QGroupBox(self.centralwidget)
        self.searchTermGroup.setEnabled(True)
        self.searchTermGroup.setAcceptDrops(False)
        self.searchTermGroup.setFlat(False)
        self.searchTermGroup.setCheckable(True)
        self.searchTermGroup.setChecked(False)
        self.searchTermGroup.setObjectName("searchTermGroup")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.searchTermGroup)
        self.verticalLayout.setObjectName("verticalLayout")
        self.searchTextEdit = QtWidgets.QPlainTextEdit(self.searchTermGroup)
        self.searchTextEdit.setObjectName("searchTextEdit")
        self.verticalLayout.addWidget(self.searchTextEdit)
        self.optionsGrid.addWidget(self.searchTermGroup, 5, 0, 1, 1)
        self.orderingGroup = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.orderingGroup.sizePolicy().hasHeightForWidth())
        self.orderingGroup.setSizePolicy(sizePolicy)
        self.orderingGroup.setObjectName("orderingGroup")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.orderingGroup)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.orderByGroup = QtWidgets.QGroupBox(self.orderingGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.orderByGroup.sizePolicy().hasHeightForWidth())
        self.orderByGroup.setSizePolicy(sizePolicy)
        self.orderByGroup.setMinimumSize(QtCore.QSize(204, 73))
        self.orderByGroup.setObjectName("orderByGroup")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.orderByGroup)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.orderDateRB = QtWidgets.QRadioButton(self.orderByGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.orderDateRB.sizePolicy().hasHeightForWidth())
        self.orderDateRB.setSizePolicy(sizePolicy)
        self.orderDateRB.setChecked(True)
        self.orderDateRB.setObjectName("orderDateRB")
        self.gridLayout_3.addWidget(self.orderDateRB, 0, 0, 1, 1)
        self.orderRelRB = QtWidgets.QRadioButton(self.orderByGroup)
        self.orderRelRB.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.orderRelRB.sizePolicy().hasHeightForWidth())
        self.orderRelRB.setSizePolicy(sizePolicy)
        self.orderRelRB.setObjectName("orderRelRB")
        self.gridLayout_3.addWidget(self.orderRelRB, 0, 3, 1, 1)
        self.orderTitleRB = QtWidgets.QRadioButton(self.orderByGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.orderTitleRB.sizePolicy().hasHeightForWidth())
        self.orderTitleRB.setSizePolicy(sizePolicy)
        self.orderTitleRB.setObjectName("orderTitleRB")
        self.gridLayout_3.addWidget(self.orderTitleRB, 0, 4, 1, 1)
        self.orderAuthorRB = QtWidgets.QRadioButton(self.orderByGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.orderAuthorRB.sizePolicy().hasHeightForWidth())
        self.orderAuthorRB.setSizePolicy(sizePolicy)
        self.orderAuthorRB.setObjectName("orderAuthorRB")
        self.gridLayout_3.addWidget(self.orderAuthorRB, 1, 0, 1, 1)
        self.orderIdRB = QtWidgets.QRadioButton(self.orderByGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.orderIdRB.sizePolicy().hasHeightForWidth())
        self.orderIdRB.setSizePolicy(sizePolicy)
        self.orderIdRB.setObjectName("orderIdRB")
        self.gridLayout_3.addWidget(self.orderIdRB, 1, 3, 1, 1)
        self.orderSlugRB = QtWidgets.QRadioButton(self.orderByGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.orderSlugRB.sizePolicy().hasHeightForWidth())
        self.orderSlugRB.setSizePolicy(sizePolicy)
        self.orderSlugRB.setObjectName("orderSlugRB")
        self.gridLayout_3.addWidget(self.orderSlugRB, 1, 4, 1, 1)
        self.horizontalLayout.addWidget(self.orderByGroup)
        self.orderInGroup = QtWidgets.QGroupBox(self.orderingGroup)
        self.orderInGroup.setObjectName("orderInGroup")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.orderInGroup)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.descendingRB = QtWidgets.QRadioButton(self.orderInGroup)
        self.descendingRB.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.descendingRB.sizePolicy().hasHeightForWidth())
        self.descendingRB.setSizePolicy(sizePolicy)
        self.descendingRB.setChecked(True)
        self.descendingRB.setObjectName("descendingRB")
        self.verticalLayout_8.addWidget(self.descendingRB)
        self.ascendingRB = QtWidgets.QRadioButton(self.orderInGroup)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ascendingRB.sizePolicy().hasHeightForWidth())
        self.ascendingRB.setSizePolicy(sizePolicy)
        self.ascendingRB.setChecked(False)
        self.ascendingRB.setAutoExclusive(True)
        self.ascendingRB.setObjectName("ascendingRB")
        self.verticalLayout_8.addWidget(self.ascendingRB)
        self.horizontalLayout.addWidget(self.orderInGroup)
        self.optionsGrid.addWidget(self.orderingGroup, 6, 0, 1, 1)
        self.additionalGroup = QtWidgets.QGroupBox(self.centralwidget)
        self.additionalGroup.setObjectName("additionalGroup")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.additionalGroup)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.postProcessCheckBox = QtWidgets.QCheckBox(self.additionalGroup)
        self.postProcessCheckBox.setToolTip("")
        self.postProcessCheckBox.setToolTipDuration(-1)
        self.postProcessCheckBox.setChecked(True)
        self.postProcessCheckBox.setObjectName("postProcessCheckBox")
        self.verticalLayout_3.addWidget(self.postProcessCheckBox)
        self.filesGroup = QtWidgets.QGroupBox(self.additionalGroup)
        self.filesGroup.setFlat(True)
        self.filesGroup.setObjectName("filesGroup")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.filesGroup)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.downloadCatButton = QtWidgets.QPushButton(self.filesGroup)
        self.downloadCatButton.setObjectName("downloadCatButton")
        self.horizontalLayout_2.addWidget(self.downloadCatButton)
        self.downloadTagButton = QtWidgets.QPushButton(self.filesGroup)
        self.downloadTagButton.setObjectName("downloadTagButton")
        self.horizontalLayout_2.addWidget(self.downloadTagButton)
        self.csvConvertCheckBox = QtWidgets.QCheckBox(self.filesGroup)
        self.csvConvertCheckBox.setChecked(True)
        self.csvConvertCheckBox.setObjectName("csvConvertCheckBox")
        self.horizontalLayout_2.addWidget(self.csvConvertCheckBox)
        self.verticalLayout_3.addWidget(self.filesGroup)
        self.optionsGrid.addWidget(self.additionalGroup, 6, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.optionsGrid)
        self.execGroup = QtWidgets.QGridLayout()
        self.execGroup.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.execGroup.setObjectName("execGroup")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar.sizePolicy().hasHeightForWidth())
        self.progressBar.setSizePolicy(sizePolicy)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.execGroup.addWidget(self.progressBar, 0, 0, 1, 1)
        self.execButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.execButton.sizePolicy().hasHeightForWidth())
        self.execButton.setSizePolicy(sizePolicy)
        self.execButton.setMinimumSize(QtCore.QSize(0, 0))
        self.execButton.setObjectName("execButton")
        self.execGroup.addWidget(self.execButton, 0, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.execGroup)
        PostDownloader.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(PostDownloader)
        self.statusBar.setObjectName("statusBar")
        PostDownloader.setStatusBar(self.statusBar)
        self.menuBar = QtWidgets.QMenuBar(PostDownloader)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 733, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuAbout = QtWidgets.QMenu(self.menuBar)
        self.menuAbout.setObjectName("menuAbout")
        PostDownloader.setMenuBar(self.menuBar)
        self.actionAbout = QtWidgets.QAction(PostDownloader)
        self.actionAbout.setObjectName("actionAbout")
        self.actionHelp = QtWidgets.QAction(PostDownloader)
        self.actionHelp.setObjectName("actionHelp")
        self.menuAbout.addAction(self.actionAbout)
        self.menuAbout.addAction(self.actionHelp)
        self.menuBar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(PostDownloader)
        self.onlyRB.toggled['bool'].connect(self.postCount.setEnabled)
        self.postsAfterCheckBox.toggled['bool'].connect(self.afterDateEdit.setEnabled)
        self.postsBeforeCheckBox.toggled['bool'].connect(self.beforeDateEdit.setEnabled)
        self.catFilterGroup.toggled['bool'].connect(PostDownloader.setCatFilter)
        self.tagFilterGroup.toggled['bool'].connect(PostDownloader.setTagFilter)
        self.orderDateRB.clicked.connect(PostDownloader.setOutputOrder)
        self.orderRelRB.clicked.connect(PostDownloader.setOutputOrder)
        self.orderTitleRB.clicked.connect(PostDownloader.setOutputOrder)
        self.orderSlugRB.clicked.connect(PostDownloader.setOutputOrder)
        self.orderIdRB.clicked.connect(PostDownloader.setOutputOrder)
        self.orderAuthorRB.clicked.connect(PostDownloader.setOutputOrder)
        self.ascendingRB.clicked.connect(PostDownloader.setOutputOrder)
        self.descendingRB.clicked.connect(PostDownloader.setOutputOrder)
        self.onlyRB.toggled['bool'].connect(PostDownloader.setPostLimit)
        self.postCount.editingFinished.connect(PostDownloader.updatePostCount)
        self.catTextEdit.textChanged.connect(PostDownloader.updateCatFilter)
        self.tagTextEdit.textChanged.connect(PostDownloader.updateTagFilter)
        self.pathEditButton.clicked.connect(PostDownloader.setOutputPath)
        self.execButton.clicked.connect(PostDownloader.executeDownload)
        self.postsAfterCheckBox.toggled['bool'].connect(PostDownloader.setDateFilter)
        self.postsBeforeCheckBox.toggled['bool'].connect(PostDownloader.setDateFilter)
        self.afterDateEdit.editingFinished.connect(PostDownloader.updateDateFilter)
        self.beforeDateEdit.editingFinished.connect(PostDownloader.updateDateFilter)
        self.actionAbout.triggered.connect(PostDownloader.launchGithubPage)
        self.actionHelp.triggered.connect(PostDownloader.launchHelpPage)
        self.searchTermGroup.toggled['bool'].connect(self.orderRelRB.setEnabled)
        self.searchTermGroup.toggled['bool'].connect(self.orderDateRB.click)
        self.downloadCatButton.clicked.connect(PostDownloader.downloadAdditional)
        self.downloadTagButton.clicked.connect(PostDownloader.downloadAdditional)
        self.csvConvertCheckBox.toggled['bool'].connect(PostDownloader.setCsvConvert)
        self.postProcessCheckBox.toggled['bool'].connect(PostDownloader.setPostProcessing)
        self.searchTermGroup.toggled['bool'].connect(PostDownloader.setSearchTerm)
        self.searchTextEdit.textChanged.connect(PostDownloader.updateSearchTerm)
        QtCore.QMetaObject.connectSlotsByName(PostDownloader)
        PostDownloader.setTabOrder(self.allRB, self.onlyRB)
        PostDownloader.setTabOrder(self.onlyRB, self.postCount)
        PostDownloader.setTabOrder(self.postCount, self.postsAfterCheckBox)
        PostDownloader.setTabOrder(self.postsAfterCheckBox, self.afterDateEdit)
        PostDownloader.setTabOrder(self.afterDateEdit, self.postsBeforeCheckBox)
        PostDownloader.setTabOrder(self.postsBeforeCheckBox, self.beforeDateEdit)
        PostDownloader.setTabOrder(self.beforeDateEdit, self.orderDateRB)
        PostDownloader.setTabOrder(self.orderDateRB, self.orderRelRB)
        PostDownloader.setTabOrder(self.orderRelRB, self.orderTitleRB)
        PostDownloader.setTabOrder(self.orderTitleRB, self.orderAuthorRB)
        PostDownloader.setTabOrder(self.orderAuthorRB, self.orderIdRB)
        PostDownloader.setTabOrder(self.orderIdRB, self.orderSlugRB)
        PostDownloader.setTabOrder(self.orderSlugRB, self.catFilterGroup)
        PostDownloader.setTabOrder(self.catFilterGroup, self.catTextEdit)
        PostDownloader.setTabOrder(self.catTextEdit, self.tagTextEdit)
        PostDownloader.setTabOrder(self.tagTextEdit, self.pathTextEdit)
        PostDownloader.setTabOrder(self.pathTextEdit, self.pathEditButton)

    def retranslateUi(self, PostDownloader):
        _translate = QtCore.QCoreApplication.translate
        PostDownloader.setWindowTitle(_translate("PostDownloader", "PostDownloader"))
        self.catFilterGroup.setTitle(_translate("PostDownloader", "Category Filter"))
        self.postCountGroup.setTitle(_translate("PostDownloader", "Post Count"))
        self.onlyRB.setText(_translate("PostDownloader", "Only the first"))
        self.allRB.setText(_translate("PostDownloader", "All posts"))
        self.dateFilterGroup.setTitle(_translate("PostDownloader", "Date Filter"))
        self.postsAfterCheckBox.setText(_translate("PostDownloader", "Get Posts After"))
        self.postsBeforeCheckBox.setText(_translate("PostDownloader", "Get Posts Before"))
        self.tagFilterGroup.setTitle(_translate("PostDownloader", "Tag Filter"))
        self.saveLocGroup.setTitle(_translate("PostDownloader", "File Save Location"))
        self.pathEditButton.setText(_translate("PostDownloader", "Change"))
        self.searchTermGroup.setTitle(_translate("PostDownloader", "Search Term"))
        self.orderingGroup.setTitle(_translate("PostDownloader", "Output Ordering"))
        self.orderByGroup.setTitle(_translate("PostDownloader", "Order By"))
        self.orderDateRB.setText(_translate("PostDownloader", "Date"))
        self.orderRelRB.setText(_translate("PostDownloader", "Relevance"))
        self.orderTitleRB.setText(_translate("PostDownloader", "Title"))
        self.orderAuthorRB.setText(_translate("PostDownloader", "Author"))
        self.orderIdRB.setText(_translate("PostDownloader", "Post ID"))
        self.orderSlugRB.setText(_translate("PostDownloader", "Slug"))
        self.orderInGroup.setTitle(_translate("PostDownloader", "In"))
        self.descendingRB.setText(_translate("PostDownloader", "Descending"))
        self.ascendingRB.setText(_translate("PostDownloader", "Ascending"))
        self.additionalGroup.setTitle(_translate("PostDownloader", "Additional Options"))
        self.postProcessCheckBox.setText(_translate("PostDownloader", "Enable post processing"))
        self.filesGroup.setTitle(_translate("PostDownloader", "Download Additional Files"))
        self.downloadCatButton.setText(_translate("PostDownloader", "Categories"))
        self.downloadTagButton.setText(_translate("PostDownloader", "Tags"))
        self.csvConvertCheckBox.setText(_translate("PostDownloader", "Also convert to CSV"))
        self.execButton.setText(_translate("PostDownloader", "PUNCH IT"))
        self.menuAbout.setTitle(_translate("PostDownloader", "Info"))
        self.actionAbout.setText(_translate("PostDownloader", "Github Repo"))
        self.actionHelp.setText(_translate("PostDownloader", "Help"))

